import Vue from 'vue';
import Router from 'vue-router';
import Layout from '../views/layout/Layout';
import AppMain from '../views/layout/components/AppMain';

const _import = require('./_import_' + process.env.NODE_ENV);
Vue.use(Router);
export const constantRouterMap = [
  { path: '/video', meta:{title:'杭州光芽科技邀您参观2019年中国无人零售大会'}, component: _import('video'), hidden: true },
  { path: '/videonew', component: _import('videonew'), hidden: true },
  { path: '/login', component: _import('login/index'), hidden: true },
  { path: '/bind', component: _import('bind/bind'), hidden: true },
  { path: '/identify', component: _import('bind/identify'), hidden: true },
  { path: '/404', component: _import('404'), hidden: true },
  { path: '/index', component: _import('index'), hidden: true },
  { path: '/super', component: _import('super/index'), hidden: true },
  { path: '/test/:param', component: _import('analysis/test'), hidden: true },
  { path: '/dataScreen', component: _import('analysis/indexNew'), hidden: false},
  { path: '/showDataScreen', component: _import('analysis/showDataScreen'), hidden: false},//展示用数据大屏,定时刷新,token运营商写死
  { path: '/showMap', component: _import('analysis/showMap'), hidden: false},//展示用点位地图,定时刷新,token运营商写死
  {
    path: '/',
    component: Layout,
    redirect: '/analysis',
    name: '首页',
    hidden: true,
    children: [
      {
        path: 'analysis',
        component: _import('analysis/indexorigin'),
      },
      // {
      //   path: 'test/:param',
      //   name: 'test',
      //   component: _import('analysis/test'),
      //   meta: { title: 'test', icon: 'analysis' },
      //   menu: '',
      // },
    ],
  },
];
export default new Router({
  // mode: 'history', //后端支持可开
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRouterMap,
});
export const asyncRouterMap = [
  {
    path: '/homeIndex',
    component: Layout,
    redirect: '/homeIndex/',
    name: '数据中心',
    meta: { title: '数据中心', icon: '' },
    menu: 'homeIndex',
    children: [
      // {
      //   path: '',
      //   name: '数据看板',
      //   component: _import('analysis/layout'),
      //   meta: { title: '数据看板', icon: '' },
      //   menu: 'homeIndex',
      // },
      {
        path: '',
        name: '设备地图',
        component: _import('analysis/map'),
        meta: { title: '设备地图', icon: '' },
        menu: 'homeIndex',
      },
      {
        path: 'index',
        name: '数据大屏',
        component: _import('analysis/index'),
        meta: { title: '数据大屏', icon: '' },
        menu: 'homeIndex',
      },
      
      // {
      //   path: 'vueQr',
      //   name: '二维码',
      //   component: _import('vueQr/vueQr'),
      //   meta: { title: 'vueQr', icon: '' },
      //   menu: '',
      // },
    ],
  },
  {
    path: '/operation',
    component: Layout,
    redirect: '/operation/',
    name: '运营管理',
    meta: { title: '运营管理', icon: '' },
    menu: 'storeSku',
    children: [
      {
        path: '',
        name: '门店运营',
        component: _import('operation/storeInfoS'),
        meta: { title: '门店运营', icon: '' },
        menu: 'storeOption',
      },
      {
        path: 'replenish/:storeCode/:storeName/:isShowRepair',
        name: '补货员配置',
        component: _import('replenishment/index'),
        meta: { title: '补货员配置', icon: '' },
        menu: 'storeOption',
        hidden: true,
      },
      {
        path: 'storeDetailsS/:id/:machineCode/:makeInventoryFlag',
        name: '门店运营详情',
        component: _import('operation/storeDetailsS'),
        meta: { title: '门店运营详情', icon: '' },
        menu: 'storeOption',
        hidden: true,
      },
      {
        path: 'salePlane/:storeCode/:machineCode',
        component: _import('saleplane/index'),
        name: '销售计划',
        meta: { title: '销售计划', icon: '' },
        menu: 'inventoryInfo',
      },
      {
        path: 'discount',
        component: _import('sale/indexNew'),
        name: '促销计划',
        meta: { title: '促销计划', icon: '' },
        menu: 'storePromotion',
      },
      {
        path: 'sku',
        component: _import('sku/index'),
        name: '商品管理',
        meta: { title: '商品管理', icon: '' },
        menu: 'goodsSku',
      },
      // {
      //   path: 'skuNew',
      //   component: _import('sku/list'),
      //   name: 'new商品管理',
      //   meta: { title: 'new商品管理', icon: '' },
      //   menu: 'goodsSku',
      // },
      {
        path: 'detail/:goodsCode',
        name: '经营情况',
        component: _import('sku/detail'),
        meta: { title: '经营情况', icon: '' },
        menu: 'orderInfo',
        hidden: true
      },
      {
        path: 'getSku',
        name: '提取商品',
        component: _import('sku/getSku'),
        meta: { title: '提取商品', icon: '' },
        menu: 'orderInfo',
        hidden: true
      },
      {
        path: 'order/:complainStatus',
        name: '订单管理',
        component: _import('operation/order'),
        meta: { title: '订单管理', icon: '' },
        menu: 'orderInfo',
      },
      // {
      //   path: 'purchase',
      //   name: '采购信息',
      //   component: _import('operation/purchase/info'),
      //   meta: { title: '采购信息', icon: 'purchase' },
      //   menu: 'purchaseInfo',
      // },
      {
        path: 'index/:storeCode/:wareId/:skuCode/:makeInventoryFlag',
        component: _import('stock/index'),
        name: '实时库存',
        meta: { title: '实时库存', icon: '' },
        menu: '',
        hidden: true,
      },
      // {
      //   path: 'replenishment',
      //   component: _import('stock/replenishment'),
      //   name: '补货信息', 
      //   meta: { title: '补货信息', icon: 'replenishment' },
      //   menu: 'purchaseInfo',
      // },
      // {
      //   path: 'refund',
      //   name: '入库报销',
      //   component: _import('operation/purchase/refund'),
      //   meta: { title: '入库报销', icon: 'purchase' },
      //   menu: 'purchaseInfo',
      // },
      {
        path: 'marketInfo/:gmtFlash1/:gmtFlash2/:channelid',
        name: '购销信息',
        component: _import('operation/marketInfo'),
        meta: { title: '购销信息', icon: '' },
        menu: 'purchaseInfo',
      },
      {
        path: 'replenishInfo',
        name: '补货信息',
        component: _import('operation/replenishInfo'),
        meta: { title: '补货信息', icon: '' },
        menu: 'repairInfo',
      },
      {
        path: 'replenishrecord',
        name: '补货考勤',
        component: _import('replenishment/record'),
        meta: { title: '补货考勤', icon: '' },
        // menu: 'workRepair',
      },
      {
        path: 'recordDetail/:repairId',
        name: '报损详情',
        component: _import('replenishment/recordDetail'),
        meta: { title: '报损详情', icon: '' },
        // menu: 'workRepair',
        hidden:true
      },
      
    ],
  },
  {
    path: '/markting',
    redirect: '/markting/',
    name: '营销管理',
    component: Layout,
    meta: { title: '营销管理', icon: '' },
    menu: 'promotionAll',
    children: [
      {
        path: '',
        component: _import('user/manage'),
        name: '用户营销',
        meta: { title: '用户营销', icon: '' },
        menu: '',
      },
      {
        path: 'userDetail/:userId/:orderCode',
        component: _import('user/detail'),
        name: '用户详情',
        meta: { title: '用户详情', icon: '' },
        menu: '',
        hidden:true
      },
      {
        path: 'GroupDetail/:marId',
        component: _import('user/groupInfo'),
        name: '分组详情',
        meta: { title: '分组详情', icon: '' },
        menu: '',
        hidden:true
      },
      // {
      //   path: 'ad',
      //   // path: '',
      //   name: '上新广告',
      //   component: _import('sales/ad'),
      //   meta: { title: '上新广告', icon: 'goodsSales' },
      //   menu: 'Advertisement',
      // },
      {
        path: 'detail/:storeCode/:time/:operatorId/:storeName',
        name: '广告详情',
        component: _import('sales/detail'),
        meta: { title: '广告详情', icon: '' },
        menu: 'Advertisement',
        hidden: true,
      },
      {
        path: 'adDetail/:id',
        name: '查看广告详情',
        component: _import('sales/adDetail'),
        meta: { title: '查看广告详情', icon: '' },
        menu: 'Advertisement',
        hidden: true,
      },
      {
        path: 'detailEdit/:id',
        name: '广告详情修改',
        component: _import('sales/detailEdit'),
        meta: { title: '广告详情修改', icon: '' },
        menu: 'Advertisement',
        hidden: true,
      },
      // {
      //   path: 'push',
      //   name: '消息推送',
      //   component: _import('push/index'),
      //   meta: { title: '消息推送', icon: 'goodsSales' },
      //   menu: 'sendMessage',
      // },
      // {
      //   path: 'push/detail/:id',
      //   name: '消息推送详情',
      //   component: _import('sales/detail'),
      //   meta: { title: '消息推送详情', icon: 'goodsSales' },
      //   menu: 'sendMessage',
      //   hidden: true,
      // },
      {
        path: 'pushIndex',
        name: '消息推送',
        component: _import('push/pushIndex'),
        meta: { title: '消息推送', icon: '' },
        menu: 'sendMessage',
      },
      {
        path: 'couponn',
        component: _import('markting/index'),
        name: '卡券设置',
        meta: { title: '卡券设置', icon: '' },
        menu: 'getCoupon',
      },
      {
        path: 'coupon',
        name: '卡券设置',
        component: _import('kupper/coupon'),
        meta: { title: '卡券设置', icon: '' },
        menu: 'coupon',
      },
      // {
      //   path: 'coupon',
      //   component: _import('markting/coupon'),
      //   name: '卡券积分',
      //   meta: { title: '卡券积分', icon: 'purchase' },
      //   menu: 'coupon',
      // },
      {
        path: 'create',
        component: _import('markting/create'),
        name: '创建优惠券',
        meta: { title: '创建优惠券', icon: '' },
        menu: 'coupon',
        hidden: true,
      },
      {
        path: 'detail/:applyId',
        component: _import('markting/detail'),
        name: '查看优惠券',
        meta: { title: '查看优惠券', icon: '' },
        menu: 'coupon',
        hidden: true,
      },
      {
        path: 'send',
        name: '发放管理',
        component: _import('markting/send'),
        meta: { title: '发放管理', icon: '' },
        menu: 'coupon',
        hidden: true,
      },
    ],
  },
  {
    path: '/finance',
    redirect: '/finance/',
    name: '财务中心',
    component: Layout,
    meta: { title: '财务中心', icon: '' },
    menu: 'financeInfo',
    children: [
      {
        path: '',
        component: _import('finance/summary'),
        name: '财务中心',
        meta: { title: '财务中心', icon: '' },
        menu: 'financeInfo',
      },
      // {
      //   path: 'index',
      //   component: _import('finance/index'),
      //   name: '订单数据',
      //   meta: { title: '订单数据', icon: '' },
      //   menu: 'finance',
      // },
      // {
      //   path: 'reimbursement',
      //   component: _import('finance/reimbursement'),
      //   name: '财务报销',
      //   meta: { title: '财务报销', icon: '' },
      //   menu: 'financeTo',
      // },
      // {
      //   path: 'bad',
      //   component: _import('finance/bad'),
      //   name: '亏损SKU',
      //   meta: { title: '亏损SKU', icon: '' },
      //   menu: 'finance',
      //   hidden: true,
      // },
      // {
      //   path: 'detail/:orderId',
      //   name: '订单详情',
      //   component: _import('finance/detail'),
      //   meta: { title: '订单详情', icon: '' },
      //   menu: 'finance',
      //   hidden: true,
      // },
      // {
      //   path: 'share',
      //   name: '分润管理',
      //   component: _import('finance/share'),
      //   meta: { title: '分润管理', icon: '' },
      //   menu: 'finance',
      // },
      {
        path: 'createShare',
        name: '创建分润方',
        component: _import('finance/createShare'),
        meta: { title: '创建分润方', icon: '' },
        menu: 'finance',
        hidden:true
      },
      {
        path: 'editShare/:distributeId',
        name: '编辑分润方',
        component: _import('finance/editShare'),
        meta: { title: '编辑分润方', icon: '' },
        menu: 'finance',
        hidden:true
      },
    ],
  },
  {
    path: '/system',
    component: Layout,
    redirect: '/system/',
    name: '系统综合',
    meta: { title: '系统综合', icon: '' },
    menu: 'systemInfo',
    children: [
      {
        path: '',
        component: _import('user/index'),
        name: '账号管理',
        meta: { title: '账号管理', icon: '' },
        menu: 'user',
      },
      {
        path: 'setting',
        component: _import('bind/setting'),
        name: '运营商设置',
        meta: { title: '运营商设置', icon: '' },
        menu: 'user',
        hidden: true,
      },
      {
        path: 'auth',
        component: _import('user/auth'),
        name: '权限管理',
        meta: { title: '权限管理', icon: '' },
        menu: 'role',
      },
      {
        path: 'storeConfig',
        name: '门店管理',
        component: _import('operation/storeConfig'),
        meta: { title: '门店管理', icon: '' },
        menu: 'storeSetting',
      },
      {
        path: 'vendConfig',
        name: '机器管理',
        component: _import('operation/vendConfig'),
        meta: { title: '机器管理', icon: '' },
        menu: 'vendSetting',
      },
      {
        path: 'vendConfig/detail/:id/:machineCode',
        name: '机器配置详情',
        component: _import('operation/vendConfigDetail'),
        meta: { title: '机器配置详情', icon: '' },
        menu: 'vendSetting',
        hidden: true,
      },
      {
        path: 'bindOperator',
        name: '机器配置',
        component: _import('bind/bindOperator'),
        meta: { title: '机器配置', icon: '' },
        menu: 'vendSetting',
        hidden: true,
      },
      {
        path: 'stock',
        component: _import('system/stock'),
        name: '仓库管理',
        meta: { title: '仓库管理', icon: '' },
        menu: 'wareInfo',
      },
      {
        path: 'system',
        name: '系统设置',
        component: _import('system/systemInfo'),
        meta: { title: '系统设置', icon: '' },
        menu: 'system',
      },
      {
        path: 'log',
        name: '操作记录',
        component: _import('system/log'),
        meta: { title: '操作记录', icon: '' },
        menu: 'log',
      },
      // {
      //   path: 'updateLog',
      //   name: '更新日志',
      //   component: _import('system/update'),
      //   meta: { title: '更新日志', icon: '' },
      //   menu: 'log',
      // },
      {
        path: 'distribution',
        component: _import('system/distribution'),
        name: '分润配置',
        meta: { title: '分润配置', icon: '' },
        menu: 'merchant',
      },
      {
        path: 'deploy/:dmId/:authType/:distributName',
        component: _import('system/deploy'),
        name: '配置',
        meta: { title: '配置', icon: '' },
        menu: 'merchant',
        hidden:true,
      },
      {
        path: 'detail/:dmId',
        component: _import('system/detail'),
        name: '查看分润信息',
        meta: { title: '查看分润信息', icon: '' },
        menu: 'merchant',
        hidden:true,
      },
      {
        path: 'createdistribution',
        component: _import('system/create'),
        name: '创建分润方',
        meta: { title: '创建分润方', icon: '' },
        menu: 'merchant',
        hidden:true,
      },
      {
        path: 'edit/:dmId',
        component: _import('system/edit'),
        name: '编辑分润方',
        meta: { title: '编辑分润方', icon: '' },
        menu: 'merchant',
        hidden:true,
      },
      // {
      //   path: 'replenishrecord',
      //   name: '补货考勤',
      //   component: _import('replenishment/record'),
      //   meta: { title: '补货考勤', icon: 'repairPlan' },
      //   // menu: 'workRepair',
      // },
      // {
      //   path: 'recordDetail/:repairId',
      //   name: '报损详情',
      //   component: _import('replenishment/recordDetail'),
      //   meta: { title: '报损详情', icon: 'repairPlan' },
      //   // menu: 'workRepair',
      //   hidden:true
      // },
      // {
      //   path: 'business',
      //   component: _import('system/business'),
      //   name: '智能运营',
      //   meta: { title: '智能运营', icon: 'purchase' },
      //   menu: 'intelligent',
      // },
    ],
  },
  {
    path: '/updateLog',
    component: Layout,
    redirect: '/updateLog',
    name: '更新日志',
    meta: { title: '更新日志', icon: '' },
    hidden:true,
    menu: '',
    children: [
      {
        path: '',
        name: '更新日志',
        component: _import('system/update'),
        meta: { title: '更新日志', icon: '' },
        hidden:true,
        menu: '',
      }
    ],
  },
  {
    path: '/kupper',
    component: Layout,
    redirect: '/kupper/',
    name: '小程序管理',
    meta: { title: '小程序管理', icon: '' },
    menu: 'pragramInfo',
    children: [
      {
        path: '',
        name: '小程序设置',
        component: _import('kupper/index'),
        meta: { title: '小程序设置', icon: '' },
        menu: 'pragramDM',
      },
      {
        path: 'getKupper',
        name: '申请管理',
        component: _import('kupper/getKupper'),
        meta: { title: '申请管理', icon: '' },
        menu: '',
      },
      // {
      //   path: 'coupon',
      //   name: '优惠券设置',
      //   component: _import('kupper/coupon'),
      //   meta: { title: '优惠券设置', icon: 'tree' },
      //   menu: '',
      // },
      // {
      //   path: 'vip',
      //   name: '会员权益',
      //   component: _import('kupper/vip'),
      //   meta: { title: '会员权益', icon: '' },
      //   menu: 'pargramEqudit',
      // },
      // {
      //   path: 'foot',
      //   name: '足迹管理',
      //   component: _import('kupper/foot'),
      //   meta: { title: '足迹管理', icon: '' },
      //   menu: 'pargramEqudit',
      // },
      {
        path: 'shop',
        name: '商城管理',
        component: _import('kupper/shop'),
        meta: { title: '商城管理', icon: '' },
        menu: 'pargramEqudit',
      },
      {
        path: 'barista',
        name: '咖啡师管理',
        component: _import('kupper/barista'),
        meta: { title: '咖啡师管理', icon: '' },
        menu: 'pargramEqudit',
      },
      {
        path: 'createBarista',
        name: '创建咖啡师',
        component: _import('kupper/createBarista'),
        meta: { title: '创建咖啡师', icon: '' },
        menu: 'pargramEqudit',
        hidden:true
      },
      {
        path: 'editBarista/:sn',
        name: '编辑咖啡师',
        component: _import('kupper/editBarista'),
        meta: { title: '编辑咖啡师', icon: '' },
        menu: 'pargramEqudit',
        hidden:true
      },
      {
        path: 'order',
        name: '订单中心',
        component: _import('kupper/order'),
        meta: { title: '订单中心', icon: '' },
        menu: 'pargramEqudit',
      },
    ],
  },
];
